<a href="https://colab.research.google.com/github/vinayavr/21_regulation-CO-PO-Automation/blob/main/Copy_of_ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:

import pandas as pd
data = pd.read_csv('Dry_Eye_Dataset - Copy.csv')
data.head()

Gender  Age  Sleep duration  Sleep quality  Stress level Blood pressure  \
0      F   24             9.5              2             1         137/89   
1      M   39             9.6              2             3         108/64   
2      F   45             5.4              1             5         134/81   
3      F   45             5.4              4             5         110/90   
4      F   42             5.7              3             2          99/67   

   Heart rate  Daily steps  Physical activity  Height  ...  Smoking  \
0          67         3000                 31     161  ...        N   
1          60        12000                 74     164  ...        N   
2          95        12000                 93     179  ...        N   
3          78        19000                 32     160  ...        N   
4          72         4000                173     179  ...        N   

  Medical issue Ongoing medication Smart device before bed  \
0             Y                  Y                       N   
1             Y                  Y                       N   
2             N                  N                       Y   
3             Y                  N                       N   
4             Y                  N                       N   

  Average screen time Blue-light filter Discomfort Eye-strain Redness in eye  \
0                 8.7                 N                     Y              Y   
1                 9.6                 Y                     N              N   
2                 4.0                 N                     Y              N   
3                 7.6                 N                     Y              N   
4                 3.5                 N                     Y              Y   

  Itchiness/Irritation in eye Dry Eye Disease  
0                           N               Y  
1                           Y               Y  
2                           N               N  
3                           Y               N  
4                           N               Y  

[5 rows x 26 columns]

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Gender                       20000 non-null  object 
 1   Age                          20000 non-null  int64  
 2   Sleep duration               20000 non-null  float64
 3   Sleep quality                20000 non-null  int64  
 4   Stress level                 20000 non-null  int64  
 5   Blood pressure               20000 non-null  object 
 6   Heart rate                   20000 non-null  int64  
 7   Daily steps                  20000 non-null  int64  
 8   Physical activity            20000 non-null  int64  
 9   Height                       20000 non-null  int64  
 10  Weight                       20000 non-null  int64  
 11  Sleep disorder               20000 non-null  object 
 12  Wake up during night         20000 non-null  object 
 13  Feel sleepy duri

In [23]:
data.describe()

Age  Sleep duration  Sleep quality  Stress level  \
count  20000.000000    20000.000000   20000.000000  20000.000000   
mean      31.422800        6.998245       2.997250      2.993750   
std        8.103717        1.731723       1.412283      1.407235   
min       18.000000        4.000000       1.000000      1.000000   
25%       24.000000        5.500000       2.000000      2.000000   
50%       31.000000        7.000000       3.000000      3.000000   
75%       39.000000        8.500000       4.000000      4.000000   
max       45.000000       10.000000       5.000000      5.000000   

         Heart rate   Daily steps  Physical activity        Height  \
count  20000.000000  20000.000000       20000.000000  20000.000000   
mean      79.912200  10536.900000          90.069750    174.865900   
std       11.808279   5752.729186          52.317283     14.719903   
min       60.000000   1000.000000           0.000000    150.000000   
25%       70.000000   6000.000000          45.000000    162.000000   
50%       80.000000  11000.000000          91.000000    175.000000   
75%       90.000000  16000.000000         135.000000    188.000000   
max      100.000000  20000.000000         180.000000    200.000000   

             Weight  Average screen time  
count  20000.000000         20000.000000  
mean      74.891850             5.519885  
std       14.733839             2.606305  
min       50.000000             1.000000  
25%       62.000000             3.300000  
50%       75.000000             5.500000  
75%       88.000000             7.800000  
max      100.000000            10.000000

In [24]:
# target(y) and features(x)

# example  : y = w1x1 + w2x2 + w3x3 + ... +wnxn

In [25]:
data.columns

Index(['Gender', 'Age', 'Sleep duration', 'Sleep quality', 'Stress level',
       'Blood pressure', 'Heart rate', 'Daily steps', 'Physical activity',
       'Height', 'Weight', 'Sleep disorder', 'Wake up during night',
       'Feel sleepy during day', 'Caffeine consumption', 'Alcohol consumption',
       'Smoking', 'Medical issue', 'Ongoing medication',
       'Smart device before bed', 'Average screen time', 'Blue-light filter',
       'Discomfort Eye-strain', 'Redness in eye',
       'Itchiness/Irritation in eye', 'Dry Eye Disease'],
      dtype='object')

In [26]:
y = data['Dry Eye Disease'] # this a 1D array (this is the target )

# This will be the independent variables
# X = data[['Gender', 'Age', 'Sleep duration', 'Sleep quality', 'Stress level',
#        'Heart rate', 'Daily steps', 'Physical activity',
#        'Height', 'Weight', 'Sleep disorder', 'Wake up during night',
#        'Feel sleepy during day', 'Caffeine consumption', 'Alcohol consumption',
#        'Smoking', 'Medical issue', 'Ongoing medication',
#        'Smart device before bed', 'Average screen time', 'Blue-light filter',
#        'Discomfort Eye-strain', 'Redness in eye',
#        'Itchiness/Irritation in eye']]#this is a 2D array



X = data[['Gender', 'Age', 'Sleep duration', 'Sleep quality','Physical activity', 'Daily steps',
       'Sleep disorder', 'Caffeine consumption', 'Alcohol consumption',
       'Smoking','Redness in eye','Discomfort Eye-strain', 'Blue-light filter']]#this is a 2D array

       #NOTE : i have removed blood pressure

bool_cols = [
    'Smoking','Alcohol consumption','Sleep disorder','Caffeine consumption','Redness in eye','Discomfort Eye-strain', 'Blue-light filter'
]




In [27]:
y.shape

(20000,)

In [28]:
X.shape

(20000, 13)

In [29]:
# sklearn is used for making models, numpy and pandas are prefered for reading data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25) # by default it splits 75% (0.75) for training and 25% (0.25) for testing

# we can use random_state =>this is use to shuffle


In [30]:
X_train.shape

(15000, 13)

In [31]:
X_test.shape

(5000, 13)

In [32]:
# #now we are going to use gini impurity

# from sklearn.tree import DecisionTreeClassifier

# gini = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth=3,min_samples_leaf=5)
# gini.fit(X_train,y_train)


In [33]:
# #now we need to encode the data using the label Encoder

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# X_train['Gender'] = le.fit_transform(X_train['Gender'])
# X_test['Gender'] = le.fit_transfrom(X_test['Gender'])

# X_train['Smoking'] = le.fit_transform(X_train['Smoking'])
# X_test['Smoking'] = le.fit_transfrom(X_test['Smoking'])

# X_train['Medical issue'] = le.fit_transform(X_train['Medical issue'])
# X_test['Medical issue'] = le.fit_transfrom(X_test['Medical issue'])

# X_train['Ongoing medication'] = le.fit_transform(X_train['Ongoing medication'])
# X_test['Ongoing medication'] = le.fit_transfrom(X_test['Ongoing medication'])

# X_train['Smart device before bed'] = le.fit_transform(X_train['Smart device before bed'])
# X_test['Smart device before bed'] = le.fit_transfrom(X_test['Smart device before bed'])

# X_train['Medical issue'] = le.fit_transform(X_train['Medical issue'])
# X_test['Medical issue'] = le.fit_transfrom(X_test['Medical issue'])

# X_train['Medical issue'] = le.fit_transform(X_train['Medical issue'])
# X_test['Medical issue'] = le.fit_transfrom(X_test['Medical issue'])

# X_train['Medical issue'] = le.fit_transform(X_train['Medical issue'])
# X_test['Medical issue'] = le.fit_transfrom(X_test['Medical issue'])



In [34]:
# bool_cols = [
#     'Smoking', 'Medical issue', 'Ongoing medication',
#     'Smart device before bed','Sleep disorder', 'Blue-light filter',
#     'Discomfort Eye-strain', 'Redness in eye',
#     'Itchiness/Irritation in eye',
#     'Wake up during night', 'Feel sleepy during day',
#     'Caffeine consumption', 'Alcohol consumption'
# ]

bool_cols = [
    'Smoking','Alcohol consumption','Sleep disorder','Caffeine consumption','Redness in eye','Discomfort Eye-strain', 'Blue-light filter'
]

for col in bool_cols:
    X_train[col] = X_train[col].map({'N': 0, 'Y': 1})
    X_test[col] = X_test[col].map({'N': 0, 'Y': 1})

#for the gender
X_train['Gender'] = X_train['Gender'].map({'M': 0, 'F': 1})
X_test['Gender'] = X_test['Gender'].map({'M': 0, 'F': 1})

# # One-hot encode remaining object type columns
# object_cols = ['Sleep disorder', 'Wake up during night', 'Feel sleepy during day', 'Caffeine consumption', 'Alcohol consumption']
# X_train = pd.get_dummies(X_train, columns=object_cols, drop_first=True)
# X_test = pd.get_dummies(X_test, columns=object_cols, drop_first=True)

In [35]:
y_train = y_train.map({'N': 0, 'Y': 1})
y_test = y_test.map({'N': 0, 'Y': 1}) # since y_train and y_test have one value alone, the index value doesnt need to be mentioned

In [36]:
#now we are going to use gini impurity

from sklearn.tree import DecisionTreeClassifier

gini =  DecisionTreeClassifier(criterion='gini', max_depth=2, min_samples_leaf=2, random_state=42) #i am changing min sample to one
gini.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, min_samples_leaf=2, random_state=42)

In [37]:
missing_rows = data[data.isnull().any(axis=1)]
display(missing_rows)

Empty DataFrame
Columns: [Gender, Age, Sleep duration, Sleep quality, Stress level, Blood pressure, Heart rate, Daily steps, Physical activity, Height, Weight, Sleep disorder, Wake up during night, Feel sleepy during day, Caffeine consumption, Alcohol consumption, Smoking, Medical issue, Ongoing medication, Smart device before bed, Average screen time, Blue-light filter, Discomfort Eye-strain, Redness in eye, Itchiness/Irritation in eye, Dry Eye Disease]
Index: []

[0 rows x 26 columns]

In [38]:
X_train.describe

<bound method NDFrame.describe of        Gender  Age  Sleep duration  Sleep quality  Physical activity  \
17326       0   23             6.0              3                157   
15886       1   32             9.7              3                 65   
87          0   38             7.0              3                147   
11711       1   42             9.5              3                 50   
1297        1   31             9.6              5                155   
...       ...  ...             ...            ...                ...   
9901        1   23             7.3              2                 86   
9445        1   45             4.2              2                118   
10463       0   37             6.7              4                145   
19877       0   29             7.0              2                122   
3667        0   18             4.6              1                 87   

       Daily steps  Sleep disorder  Caffeine consumption  Alcohol consumption  \
17326        14000               1                     0                    1   
15886        18000               0                     1                    0   
87           10000               1                     1                    1   
11711        20000               1                     1                    1   
1297          7000               1                     1                    1   
...            ...             ...                   ...                  ...   
9901          3000               1                     1                    1   
9445          1000               1                     1                    0   
10463        15000               1                     0                    1   
19877        10000               1                     0                    0   
3667         14000               1                     1                    0   

       Smoking  Redness in eye  Discomfort Eye-strain  Blue-light filter  
17326        1               1                      1                  1  
15886        1               1                      0                  0  
87           1               1                      0                  1  
11711        0               1                      1                  1  
1297         0               1                      0                  1  
...        ...             ...                    ...                ...  
9901         0               1                      0                  1  
9445         1               1                      0                  1  
10463        0               0                      0                  0  
19877        1               0                      0                  0  
3667         0               0                      0                  0  

[15000 rows x 13 columns]>

In [39]:
y_pred = gini.predict(X_test)
print("Predicted values :")
print(y_pred)

Predicted values :
[1 1 1 ... 1 1 1]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)

Accuracy :  65.74


In [44]:
print("\n=== Decision Tree (Gini Impurity) ===")
print("\nPredicted values (Gini):")
print(y_pred)

print("\nAccuracy (Gini): ", accuracy_score(y_test, y_pred) * 100)
print("\nClassification Report (Gini):\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix (Gini):\n", confusion_matrix(y_test, y_pred))


=== Decision Tree (Gini Impurity) ===

Predicted values (Gini):
[1 1 1 ... 1 1 1]

Accuracy (Gini):  65.74

Classification Report (Gini):
               precision    recall  f1-score   support

           0       0.49      0.36      0.42      1697
           1       0.71      0.81      0.76      3303

    accuracy                           0.66      5000
   macro avg       0.60      0.59      0.59      5000
weighted avg       0.64      0.66      0.64      5000


Confusion Matrix (Gini):
 [[ 616 1081]
 [ 632 2671]]


In [42]:
# we are no checking RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)


print("\nPredicted values (Random Forest):")
print(y_pred)

print("\nAccuracy (Random Forest): ", accuracy_score(y_test, y_pred) * 100)
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))




Predicted values (Random Forest):
[1 1 1 ... 1 1 1]

Accuracy (Random Forest):  65.74

Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.36      0.42      1697
           1       0.71      0.81      0.76      3303

    accuracy                           0.66      5000
   macro avg       0.60      0.59      0.59      5000
weighted avg       0.64      0.66      0.64      5000


Confusion Matrix:
 [[ 616 1081]
 [ 632 2671]]


In [1]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.svm import SVC
import pandas as pd

# Define parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'poly', 'sigmoid']
}

# Create the model
svm = SVC()

# Load the data
data = pd.read_csv('Dry_Eye_Dataset - Copy.csv')

# Define target and features
y = data['Dry Eye Disease']
X = data[['Gender', 'Age', 'Sleep duration', 'Sleep quality','Physical activity', 'Daily steps',
       'Sleep disorder', 'Caffeine consumption', 'Alcohol consumption',
       'Smoking','Redness in eye','Discomfort Eye-strain', 'Blue-light filter']]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Define boolean columns for encoding
bool_cols = [
    'Smoking','Alcohol consumption','Sleep disorder','Caffeine consumption','Redness in eye','Discomfort Eye-strain', 'Blue-light filter'
]

# Encode boolean columns
for col in bool_cols:
    X_train[col] = X_train[col].map({'N': 0, 'Y': 1})
    X_test[col] = X_test[col].map({'N': 0, 'Y': 1})

# Encode gender column
X_train['Gender'] = X_train['Gender'].map({'M': 0, 'F': 1})
X_test['Gender'] = X_test['Gender'].map({'M': 0, 'F': 1})

# Encode target variable
y_train = y_train.map({'N': 0, 'Y': 1})
y_test = y_test.map({'N': 0, 'Y': 1})

# Grid search with 5-fold cross validation
grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1)
grid_search.fit(X_train, y_train)

# Best parameters and accuracy
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_ * 100)

# Use best model for predictions
best_svm = grid_search.best_estimator_
y_pred_svm = best_svm.predict(X_test)

print("\nFinal Test Accuracy:", accuracy_score(y_test, y_pred_svm) * 100)

FileNotFoundError: [Errno 2] No such file or directory: 'Dry_Eye_Dataset - Copy.csv'